sudo: required
language: node_js
node_js:
  - "0.10.43"
cache:
  directories:
    - $HOME/.meteor
    - $HOME/.npm

before_cache:
  - rm -f $HOME/.meteor/log/*.log

before_install:
  # Download Meteor
  - PATH=$PATH:$HOME/.meteor
  - if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi

  # Install spacejam and npm dependencies
  - cd studious-octo-spork
  # - npm -g install npm@latest
  # - npm install bcrypt
  - meteor npm install
  - meteor npm rebuild

script:
  # Run the unit tests and output coverage
  - npm run test:coverage

    # Send coverage to coveralls
    #
  - cat lcov.info | ./node_modules/coveralls/bin/coveralls.js || true # ignore coveralls error

notifications:
  on_success: change
